export const RELIGION_OPTIONS = [
  'Hindu',
  'Muslim',
  'Christian',
  'Sikh',
  'Jain',
  'Buddhist',
  'Parsi',
  'Jewish',
  'Bahai',
  'Spiritual',
  'No Religion',
  'Other',
];

const CASTE_OPTIONS_BY_RELIGION = {
  Hindu: [
    'Brahmin',
    'Kshatriya',
    'Rajput',
    'Vaishya',
    'Kayastha',
    'Agarwal',
    'Baniya',
    'Yadav',
    'Maratha',
    'Lingayat',
    'Vokkaliga',
    'Nair',
    'Reddy',
    'Kamma',
    'Naidu',
    'Velama',
    'Scheduled Caste',
    'Scheduled Tribe',
    'Other',
  ],
  Muslim: [
    'Sunni',
    'Shia',
    'Syed',
    'Sheikh',
    'Pathan',
    'Mughal',
    'Ansari',
    'Qureshi',
    'Memon',
    'Bohra',
    'Other',
  ],
  Christian: [
    'Roman Catholic',
    'Protestant',
    'Syrian Christian',
    'Latin Catholic',
    'Pentecostal',
    'CSI',
    'Marthoma',
    'Orthodox',
    'Born Again',
    'Other',
  ],
  Sikh: [
    'Jat',
    'Khatri',
    'Arora',
    'Ramgarhia',
    'Lubana',
    'Mazhabi',
    'Ahluwalia',
    'Other',
  ],
  Jain: [
    'Digambar',
    'Shwetambar',
    'Oswal',
    'Porwal',
    'Agarwal Jain',
    'Other',
  ],
  Buddhist: ['Theravada', 'Mahayana', 'Vajrayana', 'Navayana', 'Other'],
  Parsi: ['Parsi'],
  Jewish: ['Bene Israel', 'Cochin', 'Baghdadi', 'Other'],
  Bahai: ['Bahai'],
  Spiritual: ['Spiritual'],
  'No Religion': ['No Religion'],
  Other: ['Other'],
};

export const PROFESSION_OPTIONS = [
  'Software Engineer',
  'Product Manager',
  'Doctor',
  'Dentist',
  'Nurse',
  'Pharmacist',
  'Chartered Accountant',
  'Banker',
  'Teacher',
  'Professor',
  'Scientist',
  'Government Officer',
  'Civil Services',
  'Lawyer',
  'Entrepreneur',
  'Business Owner',
  'Sales Professional',
  'Marketing Professional',
  'Designer',
  'Architect',
  'Consultant',
  'HR Professional',
  'Media Professional',
  'Hospitality Professional',
  'Pilot',
  'Merchant Navy',
  'Defence Services',
  'Real Estate Professional',
  'Student',
  'Homemaker',
  'Other',
];

export const EDUCATION_OPTIONS = [
  'High School',
  'Higher Secondary',
  'Diploma',
  'ITI',
  'Bachelor of Arts (BA)',
  'Bachelor of Commerce (BCom)',
  'Bachelor of Science (BSc)',
  'Bachelor of Computer Applications (BCA)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Engineering (BE)',
  'Bachelor of Technology (BTech)',
  'Bachelor of Architecture (BArch)',
  'Bachelor of Pharmacy (BPharm)',
  'Bachelor of Law (LLB)',
  'Bachelor of Education (BEd)',
  'MBBS',
  'BDS',
  'BAMS',
  'BHMS',
  'BPT',
  'MTech',
  'ME',
  'Master of Arts (MA)',
  'Master of Commerce (MCom)',
  'Master of Science (MSc)',
  'Master of Computer Applications (MCA)',
  'Master of Business Administration (MBA)',
  'Master of Pharmacy (MPharm)',
  'Master of Law (LLM)',
  'CA',
  'CS',
  'ICWA',
  'PhD',
  'Post Doctorate',
  'Other',
];

const COUNTRY_STATE_DISTRICT = {
  India: {
    'Andhra Pradesh': [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Kadapa',
      'Krishna',
      'Kurnool',
      'Nellore',
      'Prakasam',
      'Srikakulam',
      'Visakhapatnam',
      'Vizianagaram',
      'West Godavari',
    ],
    Delhi: [
      'Central Delhi',
      'East Delhi',
      'New Delhi',
      'North Delhi',
      'North East Delhi',
      'North West Delhi',
      'Shahdara',
      'South Delhi',
      'South East Delhi',
      'South West Delhi',
      'West Delhi',
    ],
    Gujarat: [
      'Ahmedabad',
      'Amreli',
      'Anand',
      'Banaskantha',
      'Bharuch',
      'Bhavnagar',
      'Gandhinagar',
      'Jamnagar',
      'Junagadh',
      'Kheda',
      'Kutch',
      'Mehsana',
      'Rajkot',
      'Surat',
      'Vadodara',
    ],
    Haryana: [
      'Ambala',
      'Bhiwani',
      'Faridabad',
      'Fatehabad',
      'Gurugram',
      'Hisar',
      'Jhajjar',
      'Jind',
      'Karnal',
      'Kurukshetra',
      'Mahendragarh',
      'Panchkula',
      'Panipat',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
      'Yamunanagar',
    ],
    Karnataka: [
      'Bagalkot',
      'Ballari',
      'Belagavi',
      'Bengaluru Rural',
      'Bengaluru Urban',
      'Bidar',
      'Chamarajanagar',
      'Chikballapur',
      'Chikkamagaluru',
      'Dakshina Kannada',
      'Davanagere',
      'Dharwad',
      'Hassan',
      'Kalaburagi',
      'Kodagu',
      'Kolar',
      'Mandya',
      'Mysuru',
      'Raichur',
      'Shivamogga',
      'Tumakuru',
      'Udupi',
      'Uttara Kannada',
      'Vijayapura',
    ],
    Kerala: [
      'Alappuzha',
      'Ernakulam',
      'Idukki',
      'Kannur',
      'Kasaragod',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Malappuram',
      'Palakkad',
      'Pathanamthitta',
      'Thiruvananthapuram',
      'Thrissur',
      'Wayanad',
    ],
    Maharashtra: [
      'Ahmednagar',
      'Akola',
      'Amravati',
      'Aurangabad',
      'Beed',
      'Bhandara',
      'Chandrapur',
      'Dhule',
      'Gadchiroli',
      'Jalgaon',
      'Kolhapur',
      'Latur',
      'Mumbai City',
      'Mumbai Suburban',
      'Nagpur',
      'Nanded',
      'Nashik',
      'Osmanabad',
      'Palghar',
      'Pune',
      'Raigad',
      'Ratnagiri',
      'Sangli',
      'Satara',
      'Solapur',
      'Thane',
      'Wardha',
      'Yavatmal',
    ],
    Odisha: [
      'Angul',
      'Balangir',
      'Balasore',
      'Bargarh',
      'Bhadrak',
      'Cuttack',
      'Deogarh',
      'Dhenkanal',
      'Ganjam',
      'Jagatsinghpur',
      'Jajpur',
      'Jharsuguda',
      'Kalahandi',
      'Kendrapara',
      'Khordha',
      'Koraput',
      'Mayurbhanj',
      'Nayagarh',
      'Puri',
      'Rayagada',
      'Sambalpur',
      'Sundargarh',
    ],
    Punjab: [
      'Amritsar',
      'Barnala',
      'Bathinda',
      'Faridkot',
      'Fatehgarh Sahib',
      'Fazilka',
      'Ferozepur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Mansa',
      'Moga',
      'Mohali',
      'Muktsar',
      'Pathankot',
      'Patiala',
      'Rupnagar',
      'Sangrur',
      'Tarn Taran',
    ],
    Rajasthan: [
      'Ajmer',
      'Alwar',
      'Banswara',
      'Baran',
      'Barmer',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Bundi',
      'Chittorgarh',
      'Dausa',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalore',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Kota',
      'Nagaur',
      'Pali',
      'Rajsamand',
      'Sikar',
      'Sirohi',
      'Tonk',
      'Udaipur',
    ],
    'Tamil Nadu': [
      'Chengalpattu',
      'Chennai',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Kanyakumari',
      'Karur',
      'Krishnagiri',
      'Madurai',
      'Nagapattinam',
      'Namakkal',
      'Nilgiris',
      'Salem',
      'Sivaganga',
      'Thanjavur',
      'Theni',
      'Thoothukudi',
      'Tiruchirappalli',
      'Tirunelveli',
      'Tiruppur',
      'Tiruvallur',
      'Tiruvannamalai',
      'Vellore',
      'Viluppuram',
      'Virudhunagar',
    ],
    Telangana: [
      'Adilabad',
      'Bhadradri Kothagudem',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Karimnagar',
      'Khammam',
      'Mahabubnagar',
      'Medak',
      'Medchal',
      'Nalgonda',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Ranga Reddy',
      'Sangareddy',
      'Siddipet',
      'Suryapet',
      'Warangal',
      'Yadadri Bhuvanagiri',
    ],
    'Uttar Pradesh': [
      'Agra',
      'Aligarh',
      'Allahabad',
      'Bareilly',
      'Bulandshahr',
      'Etawah',
      'Firozabad',
      'Gautam Buddha Nagar',
      'Ghaziabad',
      'Gorakhpur',
      'Jhansi',
      'Kanpur Nagar',
      'Lucknow',
      'Mathura',
      'Meerut',
      'Moradabad',
      'Muzaffarnagar',
      'Noida',
      'Prayagraj',
      'Saharanpur',
      'Varanasi',
    ],
    'West Bengal': [
      'Alipurduar',
      'Bankura',
      'Birbhum',
      'Cooch Behar',
      'Darjeeling',
      'Hooghly',
      'Howrah',
      'Jalpaiguri',
      'Jhargram',
      'Kolkata',
      'Malda',
      'Murshidabad',
      'Nadia',
      'North 24 Parganas',
      'Paschim Bardhaman',
      'Paschim Medinipur',
      'Purba Bardhaman',
      'Purba Medinipur',
      'Purulia',
      'South 24 Parganas',
      'Uttar Dinajpur',
    ],
  },
  'United States': {
    California: ['San Francisco', 'San Jose', 'Los Angeles', 'San Diego'],
    Illinois: ['Chicago', 'Naperville', 'Peoria', 'Springfield'],
    'New Jersey': ['Jersey City', 'Edison', 'Newark', 'Princeton'],
    'New York': ['New York City', 'Buffalo', 'Albany', 'Rochester'],
    Texas: ['Austin', 'Dallas', 'Houston', 'Irving'],
  },
  Canada: {
    Alberta: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    Ontario: ['Toronto', 'Ottawa', 'Mississauga', 'Waterloo'],
    Quebec: ['Montreal', 'Quebec City', 'Laval', 'Sherbrooke'],
    'British Columbia': ['Vancouver', 'Surrey', 'Burnaby', 'Victoria'],
  },
  Australia: {
    'New South Wales': ['Sydney', 'Newcastle', 'Wollongong', 'Parramatta'],
    Queensland: ['Brisbane', 'Gold Coast', 'Cairns', 'Townsville'],
    Victoria: ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
    'Western Australia': ['Perth', 'Fremantle', 'Bunbury', 'Mandurah'],
  },
  'United Arab Emirates': {
    'Abu Dhabi': ['Abu Dhabi', 'Al Ain', 'Madinat Zayed'],
    Dubai: ['Dubai', 'Jumeirah', 'Deira', 'Al Barsha'],
    Sharjah: ['Sharjah', 'Khor Fakkan', 'Kalba'],
  },
  'United Kingdom': {
    England: ['London', 'Manchester', 'Birmingham', 'Leicester'],
    Scotland: ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee'],
    Wales: ['Cardiff', 'Swansea', 'Newport', 'Bangor'],
  },
  Singapore: {
    Singapore: ['Central Area', 'Jurong East', 'Woodlands', 'Tampines'],
  },
};

const COUNTRY_STATE_CITY = {
  India: {
    'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati'],
    Delhi: ['New Delhi', 'Dwarka', 'Rohini', 'Saket'],
    Gujarat: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
    Haryana: ['Gurugram', 'Faridabad', 'Panipat', 'Karnal'],
    Karnataka: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubballi'],
    Kerala: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur'],
    Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Nashik'],
    Odisha: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Puri'],
    Punjab: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'],
    Rajasthan: ['Jaipur', 'Udaipur', 'Jodhpur', 'Kota'],
    'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli'],
    Telangana: ['Hyderabad', 'Warangal', 'Nizamabad', 'Khammam'],
    'Uttar Pradesh': ['Lucknow', 'Noida', 'Ghaziabad', 'Kanpur'],
    'West Bengal': ['Kolkata', 'Howrah', 'Durgapur', 'Siliguri'],
  },
  'United States': {
    California: ['San Francisco', 'San Jose', 'Los Angeles', 'San Diego'],
    Illinois: ['Chicago', 'Naperville', 'Peoria', 'Springfield'],
    'New Jersey': ['Jersey City', 'Edison', 'Newark', 'Princeton'],
    'New York': ['New York City', 'Buffalo', 'Albany', 'Rochester'],
    Texas: ['Austin', 'Dallas', 'Houston', 'Irving'],
  },
  Canada: {
    Alberta: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    Ontario: ['Toronto', 'Ottawa', 'Mississauga', 'Waterloo'],
    Quebec: ['Montreal', 'Quebec City', 'Laval', 'Sherbrooke'],
    'British Columbia': ['Vancouver', 'Surrey', 'Burnaby', 'Victoria'],
  },
  Australia: {
    'New South Wales': ['Sydney', 'Newcastle', 'Wollongong', 'Parramatta'],
    Queensland: ['Brisbane', 'Gold Coast', 'Cairns', 'Townsville'],
    Victoria: ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
    'Western Australia': ['Perth', 'Fremantle', 'Bunbury', 'Mandurah'],
  },
  'United Arab Emirates': {
    'Abu Dhabi': ['Abu Dhabi', 'Al Ain', 'Madinat Zayed'],
    Dubai: ['Dubai', 'Jumeirah', 'Deira', 'Al Barsha'],
    Sharjah: ['Sharjah', 'Khor Fakkan', 'Kalba'],
  },
  'United Kingdom': {
    England: ['London', 'Manchester', 'Birmingham', 'Leicester'],
    Scotland: ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee'],
    Wales: ['Cardiff', 'Swansea', 'Newport', 'Bangor'],
  },
  Singapore: {
    Singapore: ['Central Area', 'Jurong East', 'Woodlands', 'Tampines'],
  },
};

export const COUNTRY_OPTIONS = Object.keys(COUNTRY_STATE_DISTRICT);

export function getCasteOptions(religion) {
  return CASTE_OPTIONS_BY_RELIGION[religion] || [];
}

export function getStateOptions(country) {
  return Object.keys(COUNTRY_STATE_DISTRICT[country] || {});
}

export function getCityOptions(country, state) {
  return COUNTRY_STATE_CITY[country]?.[state] || [];
}

export function getDistrictOptions(country, state) {
  return COUNTRY_STATE_DISTRICT[country]?.[state] || [];
}

export function withSelectedOption(options = [], value = '') {
  const deduped = [...new Set(options.filter(Boolean))];
  if (!value || deduped.includes(value)) {
    return deduped;
  }

  return [value, ...deduped];
}
